from __future__ import annotations

"""Synthetic contacts across business geo zones for RAG + filter demos."""

SEED_CARDS = [
    {
        "full_name": "Maya Chen",
        "company": "HarborPay Labs",
        "title": "VP Business Development",
        "phone": "+1 (415) 555-0142",
        "email": "maya.chen@harborpay.example",
        "country": "United States",
        "timezone": "America/Los_Angeles",
        "region": "US West Coast",
        "geo_zone": "NA",
        "tags": ["payments", "fintech"],
        "notes": "Focuses on merchant acquiring and cross-border checkout for mid-market SaaS.",
    },
    {
        "full_name": "Jordan Blake",
        "company": "Pacific Bridge Capital",
        "title": "Managing Partner",
        "phone": "+1 (650) 555-0198",
        "email": "j.blake@pacificbridge.example",
        "country": "United States",
        "timezone": "America/Los_Angeles",
        "region": "US West Coast",
        "geo_zone": "NA",
        "tags": ["fund bridging", "venture capital"],
        "notes": "Arranges short-term fund bridging between LPs and growth-stage fintechs in the Bay Area.",
    },
    {
        "full_name": "Sofia Reyes",
        "company": "Cascade Settlement Co.",
        "title": "Head of Partnerships",
        "phone": "+1 (206) 555-0117",
        "email": "sofia.reyes@cascadesettle.example",
        "country": "United States",
        "timezone": "America/Los_Angeles",
        "region": "US West Coast",
        "geo_zone": "NA",
        "tags": ["payments", "banking"],
        "notes": "Seattle-based; payment rails and treasury settlement for marketplaces.",
    },
    {
        "full_name": "Kenji Watanabe",
        "company": "Redwood Rails",
        "title": "Founder & CEO",
        "phone": "+1 (408) 555-0160",
        "email": "kenji@redwoodrails.example",
        "country": "United States",
        "timezone": "America/Los_Angeles",
        "region": "US West Coast",
        "geo_zone": "NA",
        "tags": ["payments", "fintech", "fund bridging"],
        "notes": "Builds liquidity bridges for payment companies expanding from APAC into California.",
    },
    {
        "full_name": "Priya Nair",
        "company": "Beacon Acquiring",
        "title": "Director of Product",
        "phone": "+1 (213) 555-0133",
        "email": "priya.nair@beaconacq.example",
        "country": "United States",
        "timezone": "America/Los_Angeles",
        "region": "US West Coast",
        "geo_zone": "NA",
        "tags": ["payments"],
        "notes": "LA office; card-not-present acquiring and fraud tooling.",
    },
    {
        "full_name": "Ethan Cole",
        "company": "Hudson Ledger",
        "title": "Partner",
        "phone": "+1 (212) 555-0188",
        "email": "ethan.cole@hudsonledger.example",
        "country": "United States",
        "timezone": "America/New_York",
        "region": "US East Coast",
        "geo_zone": "NA",
        "tags": ["fund bridging", "venture capital"],
        "notes": "NYC fund bridging — East Coast contrast for West Coast queries.",
    },
    {
        "full_name": "Aisha Rahman",
        "company": "NovaWire",
        "title": "CTO",
        "phone": "+1 (617) 555-0121",
        "email": "aisha@novawire.example",
        "country": "United States",
        "timezone": "America/New_York",
        "region": "US East Coast",
        "geo_zone": "NA",
        "tags": ["payments", "fintech"],
        "notes": "Boston payments infrastructure.",
    },
    {
        "full_name": "Lucas Meyer",
        "company": "Golden Gate Treasury",
        "title": "Relationship Manager",
        "phone": "+1 (415) 555-0177",
        "email": "lucas.meyer@ggtreasury.example",
        "country": "United States",
        "timezone": "America/Los_Angeles",
        "region": "US West Coast",
        "geo_zone": "NA",
        "tags": ["fund bridging", "banking"],
        "notes": "SF; connects corporate treasuries with bridge facilities for payment float.",
    },
    {
        "full_name": "Derek Holt",
        "company": "Midwest Rails Bank",
        "title": "SVP Corporate Banking",
        "phone": "+1 (312) 555-0166",
        "email": "derek.holt@mwrails.example",
        "country": "United States",
        "timezone": "America/Chicago",
        "region": "US Central",
        "geo_zone": "NA",
        "tags": ["banking", "fund bridging"],
        "notes": "Chicago; mid-market treasury and bridge facilities.",
    },
    {
        "full_name": "Amelia Scott",
        "company": "Maple Corridor Capital",
        "title": "Director",
        "phone": "+1 (416) 555-0190",
        "email": "amelia.scott@maplecorridor.example",
        "country": "Canada",
        "timezone": "America/Toronto",
        "region": "Canada",
        "geo_zone": "NA",
        "tags": ["venture capital", "fintech"],
        "notes": "Toronto fintech corridor investor.",
    },
    {
        "full_name": "Wei Ling Tan",
        "company": "LionCity Pay",
        "title": "Head of BD, SEA",
        "phone": "+65 8123 4567",
        "email": "weiling.tan@lioncitypay.example",
        "country": "Singapore",
        "timezone": "Asia/Singapore",
        "region": "Singapore",
        "geo_zone": "APAC",
        "tags": ["payments", "fintech"],
        "notes": "Singapore acquiring and cross-border remittance into ASEAN.",
    },
    {
        "full_name": "Hana Suzuki",
        "company": "Kurogane Capital",
        "title": "Partner",
        "phone": "+81 3-5555-0199",
        "email": "hana.suzuki@kurogane.example",
        "country": "Japan",
        "timezone": "Asia/Tokyo",
        "region": "Tokyo",
        "geo_zone": "APAC",
        "tags": ["fund bridging", "venture capital"],
        "notes": "Tokyo; bridge financing for Japan–US fintech corridors.",
    },
    {
        "full_name": "Min-jun Park",
        "company": "HanRiver Pay",
        "title": "Head of Partnerships",
        "phone": "+82 2-555-0177",
        "email": "minjun.park@hanriverpay.example",
        "country": "South Korea",
        "timezone": "Asia/Seoul",
        "region": "Seoul",
        "geo_zone": "APAC",
        "tags": ["payments", "fintech"],
        "notes": "Seoul open-banking and merchant acquiring partnerships.",
    },
    {
        "full_name": "Aisha Rahman KL",
        "company": "Straits Settle",
        "title": "Country Manager, Malaysia",
        "phone": "+60 12-555 0188",
        "email": "aisha.kl@straitssettle.example",
        "country": "Malaysia",
        "timezone": "Asia/Kuala_Lumpur",
        "region": "Kuala Lumpur",
        "geo_zone": "APAC",
        "tags": ["payments", "banking"],
        "notes": "KL settlement rails for ASEAN SMEs.",
    },
    {
        "full_name": "Arjun Mehta",
        "company": "Deccan Rails",
        "title": "VP Product",
        "phone": "+91 98 5555 0142",
        "email": "arjun.mehta@deccanrails.example",
        "country": "India",
        "timezone": "Asia/Kolkata",
        "region": "Mumbai",
        "geo_zone": "APAC",
        "tags": ["payments", "fintech"],
        "notes": "Mumbai UPI-adjacent B2B payout infrastructure.",
    },
    {
        "full_name": "Siti Rahayu",
        "company": "Nusantara Acquiring",
        "title": "CEO",
        "phone": "+62 21 5555 0191",
        "email": "siti@nusantaraacq.example",
        "country": "Indonesia",
        "timezone": "Asia/Jakarta",
        "region": "Jakarta",
        "geo_zone": "APAC",
        "tags": ["payments"],
        "notes": "Jakarta merchant acquiring for marketplaces.",
    },
    {
        "full_name": "James Okonkwo",
        "company": "Sahel Rails",
        "title": "CEO",
        "phone": "+971 50 555 0144",
        "email": "james@sahelrails.example",
        "country": "United Arab Emirates",
        "timezone": "Asia/Dubai",
        "region": "Dubai",
        "geo_zone": "MEA",
        "tags": ["payments", "fund bridging"],
        "notes": "Dubai hub for MENA payment corridors and trade finance bridges.",
    },
    {
        "full_name": "Clara Dubois",
        "company": "Seine Ledger",
        "title": "Managing Director",
        "phone": "+33 1 55 55 01 20",
        "email": "clara.dubois@seineledger.example",
        "country": "France",
        "timezone": "Europe/Paris",
        "region": "Paris",
        "geo_zone": "EU",
        "tags": ["banking", "fund bridging"],
        "notes": "Paris; EU banking partners for cross-border settlement.",
    },
    {
        "full_name": "Mateo Alves",
        "company": "Aurora PIX",
        "title": "VP Partnerships",
        "phone": "+55 11 95555-0188",
        "email": "mateo@aurorapix.example",
        "country": "Brazil",
        "timezone": "America/Sao_Paulo",
        "region": "São Paulo",
        "geo_zone": "LATAM",
        "tags": ["payments", "fintech"],
        "notes": "São Paulo; PIX-adjacent acquiring and LatAm marketplace payouts.",
    },
    {
        "full_name": "Valeria Soto",
        "company": "Azteca Checkout",
        "title": "Head of Sales",
        "phone": "+52 55 5555 0133",
        "email": "valeria.soto@aztecacheckout.example",
        "country": "Mexico",
        "timezone": "America/Mexico_City",
        "region": "Mexico City",
        "geo_zone": "LATAM",
        "tags": ["payments"],
        "notes": "Mexico City; card-present and SPEI payout partners.",
    },
    {
        "full_name": "Nora Feldman",
        "company": "NimbusStack Cloud",
        "title": "Enterprise Account Executive",
        "phone": "+1 (206) 555-0220",
        "email": "nora.feldman@nimbusstack.example",
        "country": "United States",
        "timezone": "America/Los_Angeles",
        "region": "US West Coast",
        "geo_zone": "NA",
        "tags": ["cloud services"],
        "notes": "Seattle; AWS-style cloud migrations for mid-market SaaS.",
    },
    {
        "full_name": "Rajiv Kapoor",
        "company": "BareMetal Forge",
        "title": "Regional Sales Manager",
        "phone": "+91 80 5555 0288",
        "email": "rajiv.kapoor@baremetalforge.example",
        "country": "India",
        "timezone": "Asia/Kolkata",
        "region": "Bengaluru",
        "geo_zone": "APAC",
        "tags": ["hardware", "cloud services"],
        "notes": "Bengaluru; server and edge hardware for data centers.",
    },
    {
        "full_name": "Elena Vargas",
        "company": "Harbor & Co. Counsel",
        "title": "Partner, Cross-border",
        "phone": "+1 (212) 555-0244",
        "email": "elena.vargas@harborco.example",
        "country": "United States",
        "timezone": "America/New_York",
        "region": "US East Coast",
        "geo_zone": "NA",
        "tags": ["legal"],
        "notes": "NYC; commercial and data-privacy counsel for tech vendors.",
    },
    {
        "full_name": "Tomás Rivera",
        "company": "Mercado Norte Retail",
        "title": "Category Director",
        "phone": "+52 81 5555 0311",
        "email": "tomas.rivera@mercadonorte.example",
        "country": "Mexico",
        "timezone": "America/Mexico_City",
        "region": "Monterrey",
        "geo_zone": "LATAM",
        "tags": ["retail"],
        "notes": "Monterrey retail chain; supplier onboarding and POS rollout.",
    },
    {
        "full_name": "Ingrid Berg",
        "company": "Nordic Parcel Link",
        "title": "Head of Carrier Relations",
        "phone": "+49 30 5555 0299",
        "email": "ingrid.berg@nordicparcel.example",
        "country": "Germany",
        "timezone": "Europe/Berlin",
        "region": "Berlin",
        "geo_zone": "EU",
        "tags": ["logistics", "retail"],
        "notes": "Berlin; last-mile logistics partnerships across EU.",
    },
    {
        "full_name": "Chen Wei",
        "company": "Jade Circuit Components",
        "title": "Procurement Lead",
        "phone": "+86 21 5555 0333",
        "email": "chen.wei@jadecircuit.example",
        "country": "China",
        "timezone": "Asia/Shanghai",
        "region": "Shanghai",
        "geo_zone": "APAC",
        "tags": ["hardware"],
        "notes": "Shanghai; semiconductor and PCB supplier network.",
    },
    {
        "full_name": "Fatima Al-Hassan",
        "company": "Oasis Counsel LLP",
        "title": "Of Counsel",
        "phone": "+971 4 555 0344",
        "email": "fatima@oasiscounsel.example",
        "country": "United Arab Emirates",
        "timezone": "Asia/Dubai",
        "region": "Dubai",
        "geo_zone": "MEA",
        "tags": ["legal"],
        "notes": "Dubai; corporate structuring for regional market entry.",
    },
    {
        "full_name": "Olivia Reed",
        "company": "ShelfWise Markets",
        "title": "Vendor Manager",
        "phone": "+44 20 7555 0355",
        "email": "olivia.reed@shelfwise.example",
        "country": "United Kingdom",
        "timezone": "Europe/London",
        "region": "London",
        "geo_zone": "EU",
        "tags": ["retail"],
        "notes": "London grocery retail; private-label supplier coordination.",
    },
    {
        "full_name": "Hiro Tanaka",
        "company": "Skyline Cloud JP",
        "title": "Solutions Architect",
        "phone": "+81 3-5555-0366",
        "email": "hiro.tanaka@skylinecloud.example",
        "country": "Japan",
        "timezone": "Asia/Tokyo",
        "region": "Tokyo",
        "geo_zone": "APAC",
        "tags": ["cloud services"],
        "notes": "Tokyo; multi-cloud landing zones for enterprises.",
    },
    {
        "full_name": "Samuel Okoro",
        "company": "Sahel Hardware Hub",
        "title": "General Manager",
        "phone": "+234 1 555 0377",
        "email": "samuel@sahelhardware.example",
        "country": "Nigeria",
        "timezone": "Africa/Lagos",
        "region": "Lagos",
        "geo_zone": "MEA",
        "tags": ["hardware", "retail"],
        "notes": "Lagos; distribution of networking gear and POS terminals.",
    },
    {
        "full_name": "Grace Lim",
        "company": "Kiwi Fiber Works",
        "title": "Business Development",
        "phone": "+64 9 555 0388",
        "email": "grace.lim@kiwifiber.example",
        "country": "New Zealand",
        "timezone": "Pacific/Auckland",
        "region": "Auckland",
        "geo_zone": "APAC",
        "tags": ["cloud services", "hardware"],
        "notes": "Auckland; connectivity and edge compute for ANZ — Directory「其他」demo.",
    },
]
